server:
    port: 8001
spring:
    application:
        name: spring-cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/anjie0818/springcloud     # 配置git仓库的地址
                    search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
                    username: 18636657014@163.com                                             # git仓库的账号
                    password: anjie123                                           # git仓库的密码